src/bpp/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from bpp.views.api.clarivate import GetWoSAMRInformation
from bpp.views.api.pubmed import GetPubmedIDView
from bpp.views.api.strona_tom_nr_zeszytu import StronaTomNrZeszytuView
from bpp.views.api.uzupelnij_rok import ApiUzupelnijRokWydawnictwoZwarteView, ApiUzupelnijRokWydawnictwoCiagleView

from bpp.views.oai import OAIView
from bpp.views.api import RokHabilitacjiView, PunktacjaZrodlaView, UploadPunktacjaZrodlaView, OstatniaJednostkaIDyscyplinaView
from bpp.views.browse import UczelniaView, WydzialView, JednostkaView, \
    AutorView, ZrodlaView, ZrodloView, AutorzyView, BuildSearch, PracaView, \
    JednostkiView, \
    OldPracaView, RekordToPracaView
from bpp.views.autocomplete import WidocznaJednostkaAutocomplete, \
    AutorZUczelniAutocopmlete, GlobalNavigationAutocomplete, \
    JednostkaAutocomplete, ZrodloAutocomplete, AutorAutocomplete, \
    ZapisanyJakoAutocomplete, Wydawnictwo_NadrzedneAutocomplete, \
    PodrzednaPublikacjaHabilitacyjnaAutocomplete, \
    AdminNavigationAutocomplete, KonferencjaAutocomplete, \
    Seria_WydawniczaAutocomplete, OrganPrzyznajacyNagrodyAutocomplete, \
    WydzialAutocomplete, PublicAutorAutocomplete, LataAutocomplete, PublicWydzialAutocomplete, \
    Dyscyplina_NaukowaAutocomplete, Zewnetrzna_Baza_DanychAutocomplete, PublicKonferencjaAutocomplete, \
    Dyscyplina_Naukowa_PrzypisanieAutocomplete, WydawcaAutocomplete
from bpp.views.raporty import RankingAutorow, \
    PobranieRaportu, PodgladRaportu, KasowanieRaportu, \
    RaportJednostek2012, RaportKronikaUczelni, RaportJednostek, \
    RankingAutorowFormularz, RaportDlaKomisjiCentralnejFormularz, RaportSelector, \
    RaportAutorow
from bpp.views.raporty.raport_autorow_2012 import RaportAutorow2012
from bpp import reports

reports # PyCharm, leave that import alone, it is IMPORTANT to import it
import bpp
from django.conf import settings

urlpatterns = [
    url(r'^api/rok-habilitacji/$', csrf_exempt(RokHabilitacjiView.as_view()),
        name='api_rok_habilitacji'),
    url(r'^api/punktacja-zrodla/(?P<zrodlo_id>[\d]+)/(?P<rok>[\d]+)/$',
        csrf_exempt(PunktacjaZrodlaView.as_view()),
        name='api_punktacja_zrodla'),
    url(r'^api/upload-punktacja-zrodla/(?P<zrodlo_id>[\d]+)/(?P<rok>[\d]+)/$',
        csrf_exempt(UploadPunktacjaZrodlaView.as_view()),
        name='api_upload_punktacja_zrodla'),
    url(r'^api/ostatnia-jednostka-i-dyscyplina/$',
        csrf_exempt(OstatniaJednostkaIDyscyplinaView.as_view()),
        name='api_ostatnia_jednostka_i_dyscyplina'),
    url(r'^api/pubmed-id/$',
        csrf_exempt(GetPubmedIDView.as_view()),
        name='api_pubmed_id'),
    url(r'^api/(?P<slug>[\w-]+)/wos-amr/$',
        csrf_exempt(GetWoSAMRInformation.as_view()),
        name='api_wos_amr'),
    url(r'^api/strona-tom-nr-zeszytu/$',
        csrf_exempt(StronaTomNrZeszytuView.as_view()),
        name='api_strona_tom_nr_zeszytu'),
    url(r'^api/uzupelnij_rok_wydawnictwo_zwarte/$',
        csrf_exempt(ApiUzupelnijRokWydawnictwoZwarteView.as_view()),
        name='api_uzupelnij_rok_wydawnictwo_zwarte'),
    url(r'^api/uzupelnij_rok_wydawnictwo_ciagle/$',
        csrf_exempt(ApiUzupelnijRokWydawnictwoCiagleView.as_view()),
        name='api_uzupelnij_rok_wydawnictwo_ciagle'),

    url(r'^oai/', OAIView.as_view(), name="oai"),

    url(r'^jednostka/(?P<slug>[\w-]+)/$', JednostkaView.as_view(),
        name='browse_jednostka'),
    url(r'^jednostki/$', JednostkiView.as_view(), name="browse_jednostki"),
    url(r'^jednostki/(?P<literka>.)/$', JednostkiView.as_view(),
        name="browse_jednostki_literka"),
    url(r'^wydzial/(?P<slug>[\w-]+)/$', WydzialView.as_view(),
        name='browse_wydzial'),
    url(r'^uczelnia/(?P<slug>[\w-]+)/$',
        UczelniaView.as_view(),
        name='browse_uczelnia'),
    url(r'^uczelnia/(?P<slug>[\w-]+)/(?P<article_slug>[\w-]+)/$',
        UczelniaView.as_view(),
        name='browse_artykul'),
    url(r'^autorzy/$', AutorzyView.as_view(), name='browse_autorzy'),
    url(r'^autorzy/(?P<literka>.)/$', AutorzyView.as_view(),
        name='browse_autorzy_literka'),
    url(r'^autor/(?P<slug>[\w-]+)/$', AutorView.as_view(), name='browse_autor'),
    url(r'^zrodla/$', ZrodlaView.as_view(), name='browse_zrodla'),
    url(r'^zrodla/(?P<literka>.)/$', ZrodlaView.as_view(),
        name='browse_zrodla_literka'),
    url(r'^zrodlo/(?P<slug>[\w-]+)/$', ZrodloView.as_view(),
        name='browse_zrodlo'),

    url(r'^(?P<model>[\w_]+)/(?P<pk>[\d]+)/$', OldPracaView.as_view(), name='browse_praca_old'),
    url(r'^rekord/(?P<model>[\w_]+),(?P<pk>[\d]+)/$', PracaView.as_view(),
        name='browse_praca'),
    url(r'^rekord/(?P<content_type_id>[\d]+),(?P<object_id>[\d]+)/$', RekordToPracaView.as_view(),
        name='browse_rekord'),

    url(r'^build_search/$', BuildSearch.as_view(), name='browse_build_search'),

    url(r'^raporty/$', login_required(RaportSelector.as_view()), name='raporty'),
    url(r'^raporty/kronika_uczelni/$', login_required(RaportKronikaUczelni.as_view()), name='raport_kronika_uczelni'),
    url(r'^raporty/jednostek/$', RaportJednostek.as_view(), name='raport_jednostek_formularz'),
    url(r'^raporty/autorow/$', RaportAutorow.as_view(), name='raport_autorow_formularz'),
    url(r'^raporty/ranking-autorow/wybierz/$', RankingAutorowFormularz.as_view(), name='ranking_autorow_formularz'),
    url(r'^raporty/dla-komisji-centralnej/$', login_required(RaportDlaKomisjiCentralnejFormularz.as_view()), name='raport_dla_komisji_centralnej'),


    url(r'^raporty/pobranie/(?P<uid>[\w-]+)/$',
        login_required(PobranieRaportu.as_view()), name='pobranie-raportu'),
    url(r'^raporty/podglad/(?P<uid>[\w-]+)/skasuj/$',
        login_required(KasowanieRaportu.as_view()), name='kasowanie-raportu'),
    url(r'^raporty/podglad/(?P<uid>[\w-]+)/$',
        login_required(PodgladRaportu.as_view()), name='podglad-raportu'),

    url(r'^raporty/ranking-autorow/(?P<od_roku>\d+)/(?P<do_roku>\d+)/$',
        RankingAutorow.as_view(), name='ranking-autorow'),

    url(
        r'^raporty/raport-jednostek-2012/(?P<pk>\d+)/(?P<rok_min>\d+)-(?P<rok_max>\d+)/$',
        RaportJednostek2012.as_view(),
        name='raport-jednostek-rok-min-max'),
    url(r'^raporty/raport-jednostek-2012/(?P<pk>\d+)/(?P<rok_min>\d+)/$',
        RaportJednostek2012.as_view(), name='raport-jednostek'),

    url(
        r'^raporty/raport-autorow-2012/(?P<pk>\d+)/(?P<rok_min>\d+)-(?P<rok_max>\d+)/$',
        RaportAutorow2012.as_view(),
        name='raport-autorow-rok-min-max'),
    url(r'^raporty/raport-autorow-2012/(?P<pk>\d+)/(?P<rok_min>\d+)/$',
        RaportAutorow2012.as_view(), name='raport-autorow'),

    url(r'^$', bpp.views.root, name="root"),

    url(r'^update-multiseek-title/$', bpp.views.update_multiseek_title,
        name='update_multiseek_title'),

    url(
        r'^konferencja-autocomplete/$',
        KonferencjaAutocomplete.as_view(),
        name='konferencja-autocomplete',
    ),
    url(
        r'^public-konferencja-autocomplete/$',
        PublicKonferencjaAutocomplete.as_view(),
        name='public-konferencja-autocomplete',
    ),
    url(
        r'^wydzial-autocomplete/$',
        WydzialAutocomplete.as_view(),
        name='wydzial-autocomplete',
    ),
    url(
        r'^public-wydzial-autocomplete/$',
        PublicWydzialAutocomplete.as_view(),
        name='public-wydzial-autocomplete',
    ),
    url(
        r'^seria-wydawnicza-autocomplete/$',
        Seria_WydawniczaAutocomplete.as_view(),
        name='seria-wydawnicza-autocomplete',
    ),
    url(
        r'^organ-przyznajacy-nagrody-autocomplete/$',
        OrganPrzyznajacyNagrodyAutocomplete.as_view(),
        name='organ-przyznajacy-nagrody-autocomplete',
    ),
    url(
        r'^jednostka-widoczna-autocomplete/$',
        WidocznaJednostkaAutocomplete.as_view(),
        name='jednostka-widoczna-autocomplete',
    ),

    url(
        r'^jednostka-autocomplete/$',
        JednostkaAutocomplete.as_view(),
        name='jednostka-autocomplete',
    ),

    url(
        r'^zewnetrzna-baza-danych-autocomplete/$',
        Zewnetrzna_Baza_DanychAutocomplete.as_view(),
        name='zewnetrzna-baza-danych-autocomplete',
    ),


    url(
        r'^dyscyplina-autocomplete/$',
        Dyscyplina_NaukowaAutocomplete.as_view(),
        name='dyscyplina-autocomplete',
    ),

    url(
        r'^zrodlo-autocomplete/$',
        ZrodloAutocomplete.as_view(),
        name='zrodlo-autocomplete',
    ),

    url(
        r'^autor-z-uczelni-autocomplete/$',
        AutorZUczelniAutocopmlete.as_view(),
        name='autor-z-uczelni-autocomplete',
    ),
    url(
        r'^autor-autocomplete/$',
        AutorAutocomplete.as_view(),
        name='autor-autocomplete',
    ),
    url(
        r'^public-autor-autocomplete/$',
        PublicAutorAutocomplete.as_view(),
        name='public-autor-autocomplete',
    ),
    url(
        r'^wydawca-autocomplete/$',
        WydawcaAutocomplete.as_view(),
        name='wydawca-autocomplete'
    ),
    url(
        r'^lata-autocomplete/$',
        LataAutocomplete.as_view(),
        name='lata-autocomplete',
    ),

    url(
        r'^navigation-autocomplete/$',
        GlobalNavigationAutocomplete.as_view(),
        name='navigation-autocomplete'
    ),

    url(
        r'^admin-navigation-autocomplete/$',
        AdminNavigationAutocomplete.as_view(),
        name='admin-navigation-autocomplete'
    ),

    url(
        r'^zapisany-jako-autocomplete/$',
        ZapisanyJakoAutocomplete.as_view(),
        name='zapisany-jako-autocomplete'
    ),

    url(
        r'^wydawnictwo-nadrzedne-autocomplete/$',
        Wydawnictwo_NadrzedneAutocomplete.as_view(),
        name='wydawnictwo-nadrzedne-autocomplete'
    ),

    url(
        r'^podrzedna-publikacja-habilitacyjna-autocomplete/$',

src/django_bpp/urls.py
# -*- encoding: utf-8 -*-

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.urls import path
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog
from loginas.views import user_login
from password_policies.views import PasswordChangeDoneView, \
    PasswordChangeFormView, PasswordResetFormView, PasswordResetConfirmView, \
    PasswordResetDoneView, PasswordResetCompleteView

from bpp.forms import MyAuthenticationForm
from bpp.views.admin import WydawnictwoCiagleTozView, WydawnictwoZwarteTozView, \
    PatentTozView
from bpp.views.global_nav import global_nav_redir
from bpp.views.mymultiseek import MyMultiseekResults, \
    bpp_remove_from_removed_by_hand, bpp_remove_by_hand
from django_bpp.forms import BppPasswordChangeForm
from raport_slotow import urls as raport_slotow_urls

admin.autodiscover()

from bpp.views import favicon, root

urlpatterns = [

                  url(r'^favicon\.ico$', cache_page(60 * 60)(favicon)),

                  url(r'^admin/bpp/wydawnictwo_ciagle/toz/(?P<pk>[\d]+)/$',
                      login_required(WydawnictwoCiagleTozView.as_view()), name="admin_bpp_wydawnictwo_ciagle_toz"),
                  url(r'^admin/bpp/wydawnictwo_zwarte/toz/(?P<pk>[\d]+)/$',
                      login_required(WydawnictwoZwarteTozView.as_view()), name="admin_bpp_wydawnictwo_ciagle_toz"),
                  url(r'^admin/bpp/patent/toz/(?P<pk>[\d]+)/$', login_required(PatentTozView.as_view()),
                      name="admin_bpp_wydawnictwo_ciagle_toz"),

                  # url(r'^admin/', include(admin.site.urls)),
                  path('admin/', admin.site.urls),

                  url(r'^integrator2/',
                      include(('integrator2.urls', 'integrator2'), namespace='integrator2')),

                  url(r'^eksport_pbn/',
                      include(('eksport_pbn.urls', 'eksport_pbn'), namespace='eksport_pbn')),

                  url(
                      r'^import_dyscyplin/',
                      include(
                          ('import_dyscyplin.urls', 'import_dyscyplin'),
                          namespace='import_dyscyplin'
                      )
                  ),

                  url(r'^nowe_raporty/',
                      include(('nowe_raporty.urls', 'nowe_raporty'), namespace='nowe_raporty')),

                  path('raport_slotow/', include('raport_slotow.urls')),

                  url(r'^bpp/', include(('bpp.urls', 'bpp'), namespace='bpp')),

                  path('rozbieznosci_dyscyplin/', include('rozbieznosci_dyscyplin.urls')),

                  url(r'^multiseek/results/$',
                      csrf_exempt(MyMultiseekResults.as_view(
                          registry=settings.MULTISEEK_REGISTRY,
                          template_name="multiseek/results.html"
                      )), name="multiseek:results"),

                  url(r'^multiseek/', include(('multiseek.urls', 'multiseek'), namespace='multiseek')),

                  url(r'^multiseek/live-results/$',
                      csrf_exempt(MyMultiseekResults.as_view(
                          registry=settings.MULTISEEK_REGISTRY,
                          template_name="multiseek/live-results.html"
                      )), name="live-results"),

                  url(r'^multiseek/remove-from-results/(?P<pk>\w+)$',
                      bpp_remove_by_hand,
                      name="remove_from_results"),

                  url(r'^multiseek/remove-from-removed-results/(?P<pk>\w+)$',
                      bpp_remove_from_removed_by_hand,
                      name="remove_from_removed_results"),

                  url(r'^admin_tools/', include('admin_tools.urls')),
                  url(r'^grappelli/', include('grappelli.urls')),

                  url(r'^$', root, name="root"),

                  url(r'^accounts/login/$', LoginView.as_view(
                      authentication_form=MyAuthenticationForm), name="login_form"),

                  url(r'^password_change_done/$',
                      PasswordChangeDoneView.as_view(),
                      name="password_change_done"),
                  url(r'^password_change/$',
                      PasswordChangeFormView.as_view(form_class=BppPasswordChangeForm),
                      name="password_change"),
                  url(r"^password_reset/$",
                      PasswordResetFormView.as_view(),
                      name="password_reset"),
                  url(r'^password_reset_confirm/'
                      r'([0-9A-Za-z_\-]+)/([0-9A-Za-z]{1,13})/([0-9A-Za-z-=_]{1,32})/$',
                      PasswordResetConfirmView.as_view(),
                      name="password_reset_confirm"),
                  url(r'^password_reset_done/$',
                      PasswordResetDoneView.as_view(),
                      name="password_reset_done"),
                  url(r'^password_reset_complete/$',
                      PasswordResetCompleteView.as_view(),
                      name="password_reset_complete"),

                  url(r'^logout/$', logout, name="logout"),

                  url(r'^messages/', include(('messages_extends.urls', 'messages_extends'),
                                             namespace='messages_extends')),

                  url(r'^.*/jsi18n/$', JavaScriptCatalog.as_view(packages=[
                      'multiseek',
                  ])),

                  url(r'session_security/', include('session_security.urls')),

                  url(r"^login/user/(?P<user_id>.+)/$", user_login, name="loginas-user-login"),

                  url(r'^robots\.txt', include('robots.urls')),

                  # url(r'^sitemap\.xml$', cache_page(7*24*3600)(sitemaps_views.index), {
                  #     'sitemaps': django_bpp_sitemaps,
                  #     'sitemap_url_name': 'sitemaps'
                  # }, name='sitemap'),
                  # url(r'^sitemap-(?P<section>.+)\.xml$',
                  #     cache_page(7*24*3600)(sitemaps_views.sitemap), {'sitemaps': django_bpp_sitemaps},
                  #     name='sitemaps'),

                  # url(r'^sitemap\.xml', include('static_sitemaps.urls')),
                  path('', include('static_sitemaps.urls')),

                  url(r'', include('webmaster_verification.urls')),

                  url(r'^global-nav-redir/(?P<param>.+)/$',
                      global_nav_redir,
                      name='global-nav-redir')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.conf import settings
from django.conf.urls import include, url

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

handler404 = 'bpp.views.handler404'
handler500 = 'bpp.views.handler500'
handler403 = 'bpp.views.handler403'

src/bpp/models/dyscyplina.py
from django.db import models
from django.db.models import PositiveSmallIntegerField
from mptt.models import MPTTModel, TreeForeignKey


class Dyscyplina_Naukowa(MPTTModel):
    nazwa = models.CharField(max_length=200)
    dyscyplina_nadrzedna = TreeForeignKey(
        'self',
        null=True,
        blank=True,
        related_name='subdyscypliny',
        db_index=True)

    class MPTTMeta:
        order_insertion_by = ['nazwa']


class Autor_Dyscyplina(models.Model):
    rok = PositiveSmallIntegerField()
    autor = models.ForeignKey("bpp.Autor")
    dyscyplina = models.ForeignKey("bpp.Dyscyplina_Naukowa")

src/bpp/templates/raporty/raport_jednostek_autorow_2012/_mono.html
{% extends "django_tables2/table.html" %}

{% load i18n django_tables2 %}

{% block table.tfoot %}
    {% if table.rows %}
    <tr>
        <td colspan="{{ colspan }}" align="right" style="text-align: right;">
            <strong>Suma:</strong>
        </td>
        <td>{{ table.sum_punkty_kbn }}</td>
    </tr>
    {% endif %}
{% endblock %}

{% block pagination %}
    {# bez paginacji - wyrzucamy całą tabelę #}
{% endblock %}

src/bpp/templates/raporty/raport_jednostek_autorow_2012/monografie.html
{% include "raporty/raport_jednostek_autorow_2012/_mono.html" with colspan=7 %}

src/bpp/templates/raporty/raport_jednostek_autorow_2012/publikacje.html
{% extends "django_tables2/table.html" %}

{% load i18n django_tables2 %}

{% block table.tfoot %}
    {% if table.rows %}
    <tr>
        <td colspan="{{  table.span_rows }}" align="right" style="text-align: right;">
            <strong>Suma:</strong>
        </td>
        {% if table.print_sum_impact %}
            <td>{{ table.sum_impact }}</td>
        {% endif %}
        <td>{{ table.sum_punkty_kbn }}</td>
    </tr>
    {% endif %}
{% endblock %}

{% block pagination %}
    {# bez paginacji - wyrzucamy całą tabelę #}
{% endblock %}

src/bpp/templates/raporty/raport_jednostek_autorow_2012/raport_autorow.html
{% extends "base.html" %}

{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url "bpp:raport_jednostek_formularz" %}">Raport autorów</a></li>
    <li class="current">
        {% if rok_min != rok_max %}
            {{ autor }}, lata {{ rok_min }} - {{ rok_max }}
        {% else %}
            {{ autor }} - rok {{ rok_min }}
        {% endif %}

    </li>
{% endblock %}

{% block extratitle %}
    {% if rok_min != rok_max %}
        Raport dla {{ autor }} za okres {{ rok_min }} - {{ rok_max }}
    {% else %}
        Raport dla {{ autor }} za rok {{ rok }}
    {% endif %}
{% endblock %}

{% block extrahead %}
    {{ block.super }}
    <link rel="stylesheet"
          href="{{ STATIC_URL }}django_tables2/themes/paleblue/css/screen.css"/>
{% endblock %}

{% block content %}
    {% include "raporty/raport_jednostek_autorow_2012/raport_common.html" with object=autor %}
{% endblock %}

src/bpp/templates/raporty/raport_jednostek_autorow_2012/raport_common.html
{% load render_table from django_tables2 %}
<center>
    <h1>{{ object }}</h1>

    {% if rok_min != rok_max %}
        <h2>Dane o publikacjach za okres {{ rok_min }} - {{ rok_max }}</h2>
    {% else %}
        <h2>Dane o publikacjach za rok {{ rok_min }}</h2>
    {% endif %}
</center>
<h3>I. Osiągnięcia naukowe i twórcze</h3>
<h4>1. Publikacje w czasopismach naukowych</h4>
<h5>1.1. Publikacje w czasopiśmie naukowym posiadającym Impact Factor IF
    (część A wykazu MNiSW)</h5>
{% render_table tabela_1_1 %}
<h5>1.2 Publikacja w czasopiśmie naukowym nieposiadającym IF (część B wykazu
    MNiSW)</h5>
{% render_table tabela_1_2 %}
<h5>1.3 Publikacja w czasopiśmie naukowym znajdującym się w bazie European
    Reference Index for the Humanities (ERIH (część C wykazu MNiSW)</h5>
{% render_table tabela_1_3 %}
<h5>1.4 Recenzowana publikacja naukowa w języku innym niż polski w zagranicznym
    czasopiśmie naukowym spoza list A,B,C, o objętości co najmniej 0,5 arkusza
</h5>
{% render_table tabela_1_4 %}
<h5>1.5 Publikacja w recenzowanych materiałach z konferencji międzynarodowej
    uwzględnionej w Web of Science.</h5>
{% render_table tabela_1_5 %}

<h4>2. Monografie naukowe</h4>

<h5>2.1 Autorstwo monografii naukowej (do 3 autorów)</h5>
{% render_table tabela_2_1 %}
<h5>2.2 Autorstwo rozdziału w monografii naukowej</h5>
{% render_table tabela_2_2 %}
<h5>2.3 Redakcja naukowa monografii naukowej wieloautorskiej </h5>
{% render_table tabela_2_3 %}

src/bpp/templates/raporty/raport_jednostek_autorow_2012/raport_jednostek.html
{% extends "base.html" %}

{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url "bpp:raport_jednostek_formularz" %}">Raport jednostek</a></li>
    <li class="current">
        {% if rok_min != rok_max %}
            {{ jednostka }}, lata {{ rok_min }} - {{ rok_max }}
        {% else %}
            {{ jednostka }} - rok {{ rok_min }}
        {% endif %}

    </li>
{% endblock %}

{% block extratitle %}
    {% if rok_min != rok_max %}
        Raport dla {{ jednostka }} za okres {{ rok_min }} - {{ rok_max }}
    {% else %}
        Raport dla {{ jednostka }} za rok {{ rok }}
    {% endif %}
{% endblock %}

{% block extrahead %}
    {{ block.super }}
    <link rel="stylesheet"
          href="{{ STATIC_URL }}django_tables2/themes/paleblue/css/screen.css"/>
{% endblock %}

{% block content %}
    {% include "raporty/raport_jednostek_autorow_2012/raport_common.html" with object=jednostka %}
{% endblock %}

src/bpp/templates/raporty/raport_jednostek_autorow_2012/rozdzialy_monografii.html
{% include "raporty/raport_jednostek_autorow_2012/_mono.html" with colspan=9 %}